name: Test Local Action

on:
  push:
    branches:
      - add-github-action
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run local action
        uses: ./
        with:
          path: sample
          domain: ${{ vars.CONFLUENCE_DOMAIN }}
          username: ${{ vars.CONFLUENCE_USER_NAME }}
          api_key: ${{ secrets.CONFLUENCE_API_KEY }}
          space: ${{ vars.CONFLUENCE_SPACE_KEY }}
          root_page: 'Sample Markdown Files'
          title_prefix: 'Action Test - '
          keep_hierarchy: true
          render_diagrams: true
          diagram_format: 'svg'
